---
- name: Update PHP upload limits on existing servers
  hosts: all
  become: yes
  vars:
    php_version: "8.2"
  
  tasks:
    - name: Check if PHP is installed
      command: php --version
      register: php_check
      failed_when: false
      changed_when: false

    - name: Fail if PHP is not installed
      fail:
        msg: "PHP is not installed on this server"
      when: php_check.rc != 0

    - name: Display current PHP version
      debug:
        msg: "PHP is installed: {{ php_check.stdout_lines[0] }}"

    - name: Create PHP CLI conf.d directory if it doesn't exist
      file:
        path: "/etc/php/{{ php_version }}/cli/conf.d"
        state: directory
        mode: '0755'

    - name: Create PHP FPM conf.d directory if it doesn't exist
      file:
        path: "/etc/php/{{ php_version }}/fpm/conf.d"
        state: directory
        mode: '0755'

    - name: Configure PHP upload limits for CLI
      copy:
        src: roles/lunar2-provision/files/99-upload-limits.ini
        dest: "/etc/php/{{ php_version }}/cli/conf.d/99-upload-limits.ini"
        force: true
        backup: yes
      notify: restart php-fpm

    - name: Configure PHP upload limits for FPM
      copy:
        src: roles/lunar2-provision/files/99-upload-limits.ini
        dest: "/etc/php/{{ php_version }}/fpm/conf.d/99-upload-limits.ini"
        force: true
        backup: yes
      notify: restart php-fpm

    - name: Check if PHP-FPM service exists
      systemd:
        name: "php{{ php_version }}-fpm"
      register: php_fpm_status
      failed_when: false

    - name: Verify upload limits configuration
      shell: php -i | grep -E "(upload_max_filesize|post_max_size|max_file_uploads)"
      register: php_config_check
      changed_when: false

    - name: Display current PHP upload configuration
      debug:
        msg: "{{ php_config_check.stdout_lines }}"

  handlers:
    - name: restart php-fpm
      systemd:
        name: "php{{ php_version }}-fpm"
        state: restarted
      when: php_fpm_status.status is defined and php_fpm_status.status.ActiveState is defined
