- name: Ensure proxy_cache_path directive is present in nginx.conf
  ansible.builtin.blockinfile:
    path: /etc/nginx/nginx.conf
    marker: "# {mark} ANSIBLE HTTP CACHE"
    insertafter: "http {"
    block: |
      proxy_cache_path /tmp/cache keys_zone=my_cache:60m loader_threshold=300 loader_files=100;
    state: present
    backup: true

- name: Loop over all .conf file in /etc/nginx/conf.d/*.conf
  ansible.builtin.find:
    path: /etc/nginx/conf.d/
    patterns: "*.conf"
  register: nginx_conf_files

- name: Update server block
  with_items: "{{ nginx_conf_files.files }}"
  ansible.builtin.blockinfile:
    path: "{{ item.path }}"
    marker: "# {mark} ANSIBLE SERVER CACHE" # never change this line
    insertbefore: "locattion / {"
    block: |
      proxy_cache my_cache;
      proxy_cache_key "$host$request_uri$scheme$proxy_host";
      proxy_cache_valid 200 301 302 160h;
      proxy_ignore_headers Cache-Control Expires;
      add_header X-Proxy-Cache $upstream_cache_status;

      set $skip_cache 0;
      if ($http_authorization) {
        set $skip_cache 1;
      }
      if ($request_uri ~* ^(/lunar.*|/wp-admin.*|/cart.*|/checkout.*|/thanh-toan.*|/gio-hang.*|/api.*|/wp-json.*|.*\.php|.*\.xml)$) {
          set $skip_cache 1;
      }

      # Don't use the cache for logged in users or recent commenters
      if ($http_cookie ~* "comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in") {
          set $skip_cache 1;
      }

- name: Update location block
  with_items: "{{ nginx_conf_files.files }}"
  ansible.builtin.blockinfile:
    path: "{{ item.path }}"
    marker: "# {mark} ANSIBLE LOCATION CACHE" # never change this line
    insertafter: "location / {"
    block: |
      proxy_cache_bypass $skip_cache;
      proxy_no_cache $skip_cache;

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
