- name: Ensure proxy_cache_path directive is present in nginx.conf
  ansible.builtin.blockinfile:
    path: /etc/nginx/nginx.conf.test
    marker: "# {mark} ANSIBLE HTTP CACHE"
    insertafter: "http {"
    block: |
      proxy_cache_path /tmp/cache keys_zone=my_cache:60m loader_threshold=300 loader_files=100;
    state: present
    backup: yes
  notify: Reload nginx

- name: Loop over all .conf file in /etc/nginx/conf.d/*.conf
  ansible.builtin.find:
    paths: /etc/nginx/conf.d/
    patterns: "*.conf"
  register: nginx_conf_files

- name: debug nginx_conf_files
  ansible.builtin.debug:
    var: nginx_conf_files
