- name: Check if python3 is installed, if installed ignore other tasks
  ansible.builtin.stat:
    path: /usr/local/bin/python3.10
  register: python3_check

- name: Check python3 symlinked yet
  ansible.builtin.stat:
    path: /usr/bin/python3
  register: python3_symlink_check

- name: Create symlink for python3
  shell: ln -s /usr/local/bin/python3.10 /usr/bin/python3
  when: python3_symlink_check.stat.exists == False and python3_check.stat.exists == True

- name: Upload the python3.10 installation script
  ansible.builtin.copy:
    src: files/install-python3.sh
    dest: /tmp/install-python3.sh
    mode: 0755
  when: python3_check.stat.exists == False

- name: Run the python3.10 installation script
  shell:
    chdir: /tmp
    cmd: chmod +x install-python3.sh && ./install-python3.sh
  when: python3_check.stat.exists == False

- name: Remove the python3.10 installation script
  shell: rm -f /tmp/install-python3.sh
  when: python3_check.stat.exists == False
