# tasks/main.yml
- name: Find all WordPress plugin directories
  shell: "find /home -maxdepth 6 -type d -path '*/public_html/wp-content/plugins'"
  register: wp_plugin_dirs
  changed_when: false

- name: Set fact for plugins directories
  set_fact:
    plugin_dirs: "{{ wp_plugin_dirs.stdout_lines }}"

- name: Extract user home directories
  set_fact:
    plugin_users: "{{ plugin_dirs | map('regex_replace', '^/home/([^/]+)/.*$', '\\1') | unique | list }}"

- name: Debug the plugin directories
  debug:
    var: plugin_dirs

- name: Debug the plugin directories
  debug:
    var: plugin_users

# - name: End here
  # meta: end_play

- name: Copy plugin zip file to /tmp folder
  copy:
    src: "files/{{ plugin_zip }}"
    dest: "/tmp/{{ plugin_zip }}"
  tags: upload

- name: Unzip the plugin file in /tmp
  unarchive:
    src: "/tmp/{{ plugin_zip }}"
    dest: "/tmp"
    remote_src: yes
  tags: unzip

- name: Check if the plugin directory exists on each site
  stat:
    path: "{{ item }}/{{ plugin_name }}"
  with_items: "{{ plugin_dirs }}"
  register: plugin_dir_exists
  changed_when: false

- name: Copy plugin files from /tmp to each site if plugin exists
  copy:
    src: "/tmp/{{ plugin_name }}/"
    dest: "{{ item.item }}/{{ plugin_name }}/"
    remote_src: yes
    mode: 'u+rX'
  with_items: "{{ plugin_dir_exists.results }}"
  when: item.stat.exists
  tags: copy

- name: Change ownership of the plugin directory if plugin exists
  file:
    path: "{{ item.item }}/{{ plugin_name }}"
    state: directory
    owner: "{{ plugin_users[plugin_dirs.index(item.item)] }}"
    group: "{{ plugin_users[plugin_dirs.index(item.item)] }}"
    recurse: yes
  with_items: "{{ plugin_dir_exists.results }}"
  when: item.stat.exists

- name: Cleanup after update
  file:
    path: "/tmp/{{ plugin_name }}"
    state: absent

