# tasks/main.yml
- name: Copy plugin zip file to /tmp folder
  copy:
    src: "files/{{ plugin_zip }}"
    dest: "/tmp/{{ plugin_zip }}"
  tags: upload

- name: Copy update-plugin.sh to /tmp folder
  copy:
    src: "files/update-plugin.sh"
    dest: "/tmp/update-plugin.sh"
    mode: +x
  tags: upload

# - name: Unzip the plugin file in /tmp
#   unarchive:
#     src: "/tmp/{{ plugin_zip }}"
#     dest: "/tmp"
#     remote_src: yes
#     extra_opts:
#       - -j
#   tags: unzip

- name: Run the update-plugin.sh script
  args:
    chdir: /tmp
  shell: chmod +x update-plugin.sh && ./update-plugin.sh "{{ plugin_zip }}" "{{ plugin_name }}"