---
- name: install nodejs version 21
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash -
    sudo apt-get install -y nodejs

- name: Download and install Composer
  shell: |
    sudo curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
    sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

- name: Install pnpm
  shell: npm install -g pnpm