---
- name: update all package
  apt: name="*" state=latest

- name: change sysctl config file
  template:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    backup: yes

- name: Create ~/.ssh directory if it doesn't exist
  file:
    path: ~/.ssh
    state: directory
    mode: '0700'

- name: Add github.com configuration to ssh_config
  lineinfile:
    path: /etc/ssh/ssh_config
    insertbefore: '^Host \*'
    line: |
      Host github.com
      HostName github.com
      IdentityFile ~/.ssh/deploy_rsa.pem

- name: Copy deploy RSA key
  copy:
    src: /opt/key_deploy/id_rsa_deploy
    dest: ~/.ssh/deploy_rsa.pem
    mode: 0600

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - lsb-release
    - gnupg2
    - ca-certificates
    - apt-transport-https
    - software-properties-common
    - net-tools
    - jpegoptim
    - optipng
    - pngquant
    - git
    - python3-pip
    - snap
    - snapd

- name: Add php repository
  shell: echo "yes" | sudo add-apt-repository ppa:ondrej/php

- name: install php 8.2
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php8.2
    - php8.2-fpm
    - php8.2-bcmath
    - php8.2-xml
    - php8.2-mysql
    - php8.2-zip
    - php8.2-intl
    - php8.2-ldap
    - php8.2-gd
    - php8.2-cli
    - php8.2-bz2
    - php8.2-curl
    - php8.2-mbstring
    - php8.2-pgsql
    - php8.2-opcache
    - php8.2-soap
    - php8.2-cgi
    - build-essential
    - php8.2-dev

- name: pecl install php-redis
  shell: sudo echo -e "\n\n\n\n\n\n" | sudo pecl install redis
  ignore_errors: yes

- name: Enable UFW (Uncomplicated Firewall)
  ufw:
    state: enabled

- name: Allow SSH (port 22) through UFW
  ufw:
    rule: allow
    port: 22

- name: Allow HTTP (port 80) through UFW
  ufw:
    rule: allow
    port: 80

- name: Allow HTTPS (port 443) through UFW
  ufw:
    rule: allow
    port: 443

- name: Allow Zabbix-agent (port 10050) through UFW
  ufw:
    rule: allow
    port: 10050

- name: add redis.ini
  shell: sudo echo 'extension="/usr/lib/php/20220829/redis.so"' > /etc/php/8.2/mods-available/redis.ini

- name: symbolic link redis extension
  shell: sudo ln -s /etc/php/8.2/mods-available/redis.ini /etc/php/8.2/cli/conf.d/20-redis.ini && sudo ln -s /etc/php/8.2/mods-available/redis.ini /etc/php/8.2/fpm/conf.d/redis.ini
  ignore_errors: yes

- name: start php8.2-fpm
  systemd:
    name: php8.2-fpm
    state: started
    enabled: yes

- name: install redis-server
  apt:
    name: redis-server
    state: present

- name: start and enable redis server
  systemd:
    name: redis-server
    state: started
    enabled: yes

- name: install nodejs version 21
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash -
    sudo apt-get install -y nodejs

- name: Download and install Composer
  shell: |
    sudo curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
    sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

- name: Install pnpm
  shell: npm install -g pnpm

- name: change limit config file
  blockinfile:
    path: /etc/security/limits.conf
    block: |
      * soft nproc 102400
      * hard nproc 102400
      * soft nofile 102400
      * hard nofile 102400

- name: install zabbix-agent
  apt:
    name: zabbix-agent
    state: present

- name: start and enable zabbix agent
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes

- name: create folder zabbix agent
  file:
    path: /etc/zabbix/zabbix_agentd.d/
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'
  tags:
    - zabbix

- name: copy lld-disks.py
  copy:
    src: templates/lld-disks.py
    dest: /usr/local/bin/lld-disks.py
    owner: zabbix
    group: zabbix
  tags:
    - zabbix

- name: copy zabbix-agent config
  copy:
    src: templates/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: zabbix
    group: zabbix
    mode: '0644'
    backup: yes
  tags:
    - zabbix

- name: copy userparameter_diskstats.conf
  template:
    src: userparameter_diskstats.conf
    dest: /etc/zabbix/zabbix_agentd.d/userparameter_diskstats.conf
  tags:
    - zabbix

- name: copy userparameter_sockstat.conf
  template:
    src: userparameter_sockstat.conf
    dest: /etc/zabbix/zabbix_agentd.d/userparameter_sockstat.conf
  tags:
    - zabbix

- name: get hostname to config zabbix agentd
  shell: hostname
  register: hst
  tags:
    - zabbix

- name: config hostname zabbix agentd
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Hostname='
    line: Hostname={{ hst.stdout }}
  tags:
    - zabbix

- name: config IP server zabbix agentd
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server='
    line: Server=103.97.124.136
  tags:
    - zabbix

- name: config IP ServerActive zabbix agentd
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^ServerActive='
    line: ServerActive=103.97.124.136
  tags:
    - zabbix

- name: make sure folder zabbix owner by zabbix user
  shell: "chown zabbix: -R /etc/zabbix"
  tags:
    - zabbix

- name: start zabbix agent service
  systemd:
    state: started
    name: zabbix-agent
    enabled: yes
  tags:
    - zabbix

- name: check zabbix-agent is running
  shell: netstat -nltp | grep -v grep | grep zabbix
  register: zabbixagent
  tags:
    - zabbix

- debug:
    msg: "{{ zabbixagent.stdout_lines|list }}"
  tags:
    - zabbix
