- name: Upload runner script to hosts:
  copy:
    src: files/lunar-artisan.sh
    dest: /tmp/lunar-artisan.sh
    mode: +x

- name: Run the runner script
  args:
    chdir: /tmp
  shell: chmod +x lunar-artisan.sh && ./lunar-artisan.sh
  register: result

- name: Display results
  debug:
    var: result