# code: language = ansible
- name: Copy file to remote host
  copy:
    src: files/{{ item }}
    dest: /tmp/
  with_items:
    - lunar-ci.sh

- name: Make sure execute pers bash file
  shell: chmod a+x /tmp/lunar-ci.sh

- name: Run script
  shell: "./lunar-ci.sh"
  args:
    chdir: "/tmp"
  register: console

- debug:
    var: console.stdout_lines