---
- name: update all package
  apt: name="*" state=latest

- name: change sysctl config file
  template:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    backup: yes

- name: Create ~/.ssh directory if it doesn't exist
  file:
    path: ~/.ssh
    state: directory
    mode: '0700'

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - lsb-release
    - ca-certificates
    - apt-transport-https
    - software-properties-common
    - net-tools
    - python3-pip
    - snap
    - snapd

- name: Add Nginx Mainline repository
  shell: echo "yes" | sudo add-apt-repository ppa:ondrej/nginx-mainline

- name: install nginx
  apt:
    name: nginx
    state: present

- name: copy config nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    backup: yes

- name: start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: create folder contains log nginx
  file:
    path: /var/log/nginx/domains
    state: directory
    mode: '0755'

- name: Enable UFW (Uncomplicated Firewall)
  ufw:
    state: enabled

- name: Allow SSH (port 22) through UFW
  ufw:
    rule: allow
    port: 22

- name: Allow HTTP (port 80) through UFW
  ufw:
    rule: allow
    port: 80

- name: Allow HTTPS (port 443) through UFW
  ufw:
    rule: allow
    port: 443

- name: Allow Zabbix-agent (port 10050) through UFW
  ufw:
    rule: allow
    port: 10050

- name: change limit config file
  blockinfile:
    path: /etc/security/limits.conf
    block: |
      * soft nproc 102400
      * hard nproc 102400
      * soft nofile 102400
      * hard nofile 102400

- name: install zabbix-agent
  apt:
    name: zabbix-agent
    state: present

- name: start and enable zabbix agent
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes

- name: create folder zabbix agent
  file:
    path: /etc/zabbix/zabbix_agentd.d/
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'
  tags:
    - zabbix

- name: copy lld-disks.py
  copy:
    src: templates/lld-disks.py
    dest: /usr/local/bin/lld-disks.py
    owner: zabbix
    group: zabbix
  tags:
    - zabbix

- name: copy zabbix-agent config
  copy:
    src: templates/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: zabbix
    group: zabbix
    mode: '0644'
    backup: yes
  tags:
    - zabbix

- name: copy userparameter_diskstats.conf
  template:
    src: userparameter_diskstats.conf
    dest: /etc/zabbix/zabbix_agentd.d/userparameter_diskstats.conf
  tags:
    - zabbix

- name: copy userparameter_sockstat.conf
  template:
    src: userparameter_sockstat.conf
    dest: /etc/zabbix/zabbix_agentd.d/userparameter_sockstat.conf
  tags:
    - zabbix

- name: get hostname to config zabbix agentd
  shell: hostname
  register: hst
  tags:
    - zabbix

- name: config hostname zabbix agentd
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Hostname='
    line: Hostname={{ hst.stdout }}
  tags:
    - zabbix

- name: config IP server zabbix agentd
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server='
    line: Server=103.97.124.136
  tags:
    - zabbix

- name: config IP ServerActive zabbix agentd
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^ServerActive='
    line: ServerActive=103.97.124.136
  tags:
    - zabbix

- name: make sure folder zabbix owner by zabbix user
  shell: "chown zabbix: -R /etc/zabbix"
  tags:
    - zabbix

- name: start zabbix agent service
  systemd:
    state: started
    name: zabbix-agent
    enabled: yes
  tags:
    - zabbix

- name: check zabbix-agent is running
  shell: netstat -nltp | grep -v grep | grep zabbix
  register: zabbixagent
  tags:
    - zabbix

- debug:
    msg: "{{ zabbixagent.stdout_lines|list }}"
  tags:
    - zabbix

- name: install mysql 8
  apt:
    name: mysql-server
    state: present

- name: random string
  shell: head /dev/urandom | tr -dc A-Za-z0-9 | head -c 12 ; echo ''
  delegate_to: localhost
  register: rand

- name: create user password mysql
  copy:
    content: |
      [client]
      user=root
      password="{{rand.stdout}}"
    dest: /root/.my.cnf

- name: create user password mysql 2
  copy:
    content:
        "[client] user=root password={{rand.stdout}}"
    dest: /home/deploy/.my.cnf

- name: start and enable mysql server
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: Change the authentication plugin of MySQL root user to mysql_native_password
  shell: sudo mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password" WHERE user="root" AND host="localhost"'
  ignore_errors: yes

- name: install plugin validate password
  shell: sudo mysql -u root -e "INSTALL PLUGIN validate_password SONAME 'validate_password.so';"
  ignore_errors: yes

- name: modify password policy to LOW
  shell: sudo mysql -u root -e 'SET GLOBAL validate_password_policy=LOW;'
  ignore_errors: yes

- name: modify password length
  shell: sudo mysql -u root -e 'SET GLOBAL validate_password_length=8;'
  ignore_errors: yes

- name: Flush Privileges
  shell: sudo mysql -u root -e 'FLUSH PRIVILEGES'
  ignore_errors: yes

- name: Set MySQL root password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: '{{rand.stdout}}'
    state: present
  become_user: deploy
  ignore_errors: yes


- name: Add validate_password_policy line to mysqld.cnf
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    insertafter: '^\\[mysqld\\]'
    line: 'validate_password_policy = LOW'

- name: add ssh config for git pem
  blockinfile:
    path: /etc/ssh/ssh_config
    block: |
      Host github.com
      HostName github.com
      IdentityFile ~/.ssh/deploy_rsa.pem

- name: copy rsa git from local to remote host
  copy:
    src: /opt/lunarcommerce/deploy_rsa.pem
    dest: /root/.ssh/deploy_rsa.pem
    mode: 0400
    owner: root
    group: root

- name: enable systemd service
  shell: systemctl enable --now snapd.socket && ln -s /var/lib/snapd/snap /snap
  ignore_errors: yes
  tags:
    - snap

- name: Install snap
  snap:
    name:
      - core
  tags:
    - snap

- name: ensure snap is up to date - refresh core
  command: sudo snap refresh core
  tags:
    - snap

- name: Install "certbot" with option --classic
  snap:
    name: certbot
    classic: yes
  tags:
    - snap

- name: prepare cerbot command
  shell: sudo ln -s /snap/bin/certbot /usr/bin/certbot
  ignore_errors: yes
  tags:
    - snap
- name: test automatic renewal
  shell: sudo certbot renew --dry-run
  ignore_errors: yes
  register: renewal
  tags:
    - snap
- debug:
    var: renewval.stdout_lines
  tags:
    - snap

- name: list crontab
  command: systemctl list-timers
  register: list_timer
  tags:
    - snap
- debug:
    var: list_timer.stdout_lines
  tags:
    - snap

- name: make sure apache2 not install
  apt:
    name: apache2
    state: absent
  ignore_errors: yes

