---
- name: update all package
  apt:
    name="*"
    state=latest

- name: change sysctl config file
  template:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    backup: yes

- name: Create ~/.ssh directory if it doesn't exist
  file:
    path: ~/.ssh
    state: directory
    mode: '0700'

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - lsb-release
    - ca-certificates
    - apt-transport-https
    - software-properties-common
    - net-tools
    - python3-pip
    - snap
    - snapd


- ansible.builtin.import_tasks:
    file: install-nginx.yml

- name: Enable UFW (Uncomplicated Firewall)
  ufw:
    state: enabled
- ansible.builtin.import_tasks:
    file: open-ports.yml

- name: change limit config file
  blockinfile:
    path: /etc/security/limits.conf
    block: |
      * soft nproc 102400
      * hard nproc 102400
      * soft nofile 102400
      * hard nofile 102400

- ansible.builtin.import_tasks:
    file: install-zabbix.yml

- name: enable systemd service
  shell: systemctl enable --now snapd.socket && ln -s /var/lib/snapd/snap /snap
  ignore_errors: yes
  tags:
    - snap

- name: Install snap core
  snap:
    name:
      - core
  tags:
    - snap

- name: ensure snap is up to date - refresh core
  command: sudo snap refresh core
  tags:
    - snap

- name: Install "certbot" with option --classic
  snap:
    name: certbot
    classic: yes
  tags:
    - snap

- name: prepare cerbot command
  shell: sudo ln -s /snap/bin/certbot /usr/bin/certbot
  ignore_errors: yes
  tags:
    - snap

- name: test automatic renewal
  shell: sudo certbot renew --dry-run
  ignore_errors: yes
  register: renewal
  tags:
    - snap

- debug:
    var: renewval.stdout_lines
  tags:
    - snap

- name: list crontab
  command: systemctl list-timers
  register: list_timer
  tags:
    - snap
- debug:
    var: list_timer.stdout_lines
  tags:
    - snap

- name: make sure apache2 not install
  apt:
    name: apache2
    state: absent
  ignore_errors: yes

