---
- name: Install UFW if not installed
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow SSH connections
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP (port 80)
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow HTTPS (port 443)
  ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Enable UFW and set default policies
  ufw:
    state: enabled
    default: deny
    policy: reject
  register: ufw_status
  failed_when: ufw_status is failed and "already enabled" not in ufw_status.msg