# tasks/main.yml
- name: Find all WordPress plugin directories
  find:
    paths: "/home"
    patterns: "public_html/wp-content/plugins"
    recurse: yes
    file_type: directory
  register: wp_plugin_dirs

- name: Copy plugin zip file to each site
  copy:
    src: "files/{{ plugin_zip }}"
    dest: "{{ item.path }}/{{ plugin_zip }}"
  with_items: "{{ wp_plugin_dirs.files }}"
  tags: unzip

- name: Unzip the plugin file for each site
  unarchive:
    src: "{{ item.path }}/{{ plugin_zip }}"
    dest: "{{ item.path }}"
    remote_src: yes
  with_items: "{{ wp_plugin_dirs.files }}"
  tags: unzip

- name: Remove the plugin zip file after unzipping
  file:
    path: "{{ item.path }}/{{ plugin_zip }}"
    state: absent
  with_items: "{{ wp_plugin_dirs.files }}"

- name: Activate the plugin for each site
  command: wp-cli plugin activate {{ plugin_name }} --path={{ item.path | regex_replace('/wp-content/plugins', '') }}
  with_items: "{{ wp_plugin_dirs.files }}"
  register: plugin_activation
  failed_when: "'Plugin '{{ plugin_name }}' activated' not in plugin_activation.stdout"
  changed_when: "'Plugin '{{ plugin_name }}' activated' in plugin_activation.stdout"
