# tasks/main.yml
- name: Copy plugin zip file to /tmp folder
  copy:
    src: "files/{{ plugin_zip }}"
    dest: "/tmp/{{ plugin_zip }}"
  tags: upload

- name: Unzip the plugin file in /tmp
  unarchive:
    src: "/tmp/{{ plugin_zip }}"
    dest: "/tmp"
    remote_src: yes
  tags: unzip

- name: Upload the install-plugin.sh script to /tmp
  copy:
    src: "files/install-plugin.sh"
    dest: "/tmp/install-plugin.sh"
    mode: '0755'  # Ensure the script is executable
  tags: script

- name: Execute plugin install script
  shell: "/tmp/install-plugin.sh {{ plugin_zip }} {{ plugin_name }}"
  register: plugin_update_log
  ignore_errors: yes  # Continue even if the script fails
  tags: execute

- name: Show plugin update script output
  debug:
    msg: "{{ plugin_update_log }}"
