# tasks/main.yml
- name: Copy plugin zip file to /tmp folder
  copy:
    src: "files/{{ plugin_zip }}"
    dest: "/tmp/{{ plugin_zip }}"
  tags: upload

- name: Unzip the plugin file in /tmp
  unarchive:
    src: "/tmp/{{ plugin_zip }}"
    dest: "/tmp"
    remote_src: yes
  tags: unzip

- name: Upload the update_plugin.sh script to /tmp
  copy:
    src: "files/update_plugin.sh"
    dest: "/tmp/update_plugin.sh"
    mode: '0755'  # Ensure the script is executable
  tags: script

- name: Execute plugin update script
  shell: "/tmp/update_plugin.sh {{ plugin_zip }} {{ plugin_name }}"
  tags: execute