# tasks/main.yml
- name: Find all WordPress plugin directories
  shell: "find /home -type d -path '*/public_html/wp-content/plugins'"
  register: wp_plugin_dirs
  changed_when: false

- name: Set fact for plugins directories
  set_fact:
    plugin_dirs: "{{ wp_plugin_dirs.stdout_lines }}"

- name: Extract user home directories
  set_fact:
    plugin_users: "{{ plugin_dirs | map('regex_replace', '/home/(.*)/domains/(.*)/public_html/wp-content/plugins', '\\1') | map('basename') | list }}"

- name: Debug the plugin directories
  debug:
    var: plugin_users

# - name: End here
#   meta: end_play

- name: Copy plugin zip file to each site
  copy:
    src: "{{ plugin_zip }}"
    dest: "{{ item }}/{{ plugin_zip }}"
  with_items: "{{ plugin_dirs }}"
  tags: unzip

- name: Unzip the plugin file for each site
  unarchive:
    src: "{{ item }}/{{ plugin_zip }}"
    dest: "{{ item }}"
    remote_src: yes
  with_items: "{{ plugin_dirs }}"
  tags: unzip

- name: Change ownership of the plugin directory
  file:
    path: "{{ item }}/{{ plugin_name }}"
    state: directory
    owner: "{{ plugin_users[plugin_dirs.index(item)] }}"
    group: "{{ plugin_users[plugin_dirs.index(item)] }}"
    recurse: yes
  with_items: "{{ plugin_dirs }}"

- name: Activate the plugin for each site
  shell: php -d memory_limit=512M /usr/bin/wp-cli plugin activate "{{ plugin_name }}" --path={{ item | regex_replace('/wp-content/plugins', '') }} --allow-root
  with_items: "{{ plugin_dirs }}"
  register: plugin_activation
  failed_when: "'Success' not in plugin_activation.stdout"
  changed_when: "'Success' in plugin_activation.stdout"

- name: Remove the plugin zip file after unzipping
  file:
    path: "{{ item }}/{{ plugin_zip }}"
    state: absent
  with_items: "{{ plugin_dirs }}"