- name: Upload script file
  ansible.builtin.copy:
    src: "/files/run.sh"
    dest: "/tmp"

- name: Run script
  ansible.builtin.shell:
    chdir: "/tmp"
    cmd: |
      chmod +x run.sh
      ./run.sh