- name: Upload tune-rocket.sh script file
  copy:
    src: "files/tune-rocket.sh"
    dest: "/tmp"

- name: Run script tune-rocket.sh
  shell:
    chdir: "/tmp"
    cmd: |
      chmod +x tune-rocket.sh
      ./tune-rocket.sh