---
- name: "Add 2GB swap file"
  hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: "Create swap file"
      command: "fallocate -l 8G /swapfile"
      args:
        creates: "/swapfile"

    - name: "Set permissions on swap file"
      command: "chmod 600 /swapfile"

    - name: "Set up swap area"
      command: "mkswap /swapfile"

    - name: "Enable swap"
      command: "swapon /swapfile"
