##Only use this playbook if using caddy as web server
- name: Config php-fpm
  hosts: all
  become: yes

  tasks:
    - name: Set PHP upload_max_filesize and post_max_size
      lineinfile:
        path: /etc/php/8.1/fpm/php.ini
        regexp: '^upload_max_filesize\s*='
        line: 'upload_max_filesize = 256M'
        state: present
        backup: yes

    - name: Set PHP post_max_size
      lineinfile:
        path: /etc/php/8.1/fpm/php.ini
        regexp: '^post_max_size\s*='
        line: 'post_max_size = 256M'
        state: present
        backup: yes

    - name: Restart PHP-FPM to apply upload size changes
      systemd:
        name: php8.1-fpm
        state: restarted



#ansible-playbook -i 89.117.53.180, playbooks/config-phpfpm.yml -u root

#/var/www - if installing phpmyadin in /var/www