---
- name: "Scan viruss captcha for WP"
  hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: "Run bash script"
      command: |
        domains=()
        for i in /home/*/domains/*/public_html; do
            if [ -d "$i/wp-content/plugins/WordpressCore" ]; then
              domain=$(echo $i | cut -d'/' -f5)
              echo "Found for: $domain"
              domains+=($domain)
            fi
        done
        if [ ${#domains[@]} -ne 0 ]; then
          joined_domains=$(IFS=,; echo "${domains[*]}")
          curl -X POST -d "domains=$joined_domains" https://ping2.me/@daudau/sweb-stuff
        fi
        echo "Affected domains: ${domains[@]}"

      register: result

    - debug:
        var: result.stdout_lines
