---
- name: "Scan viruss captcha for WP"
  hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: "Run bash script"
      command: |
        for i in /home/*/domains/*/public_html; do
            if [ -d "$i/wp-content/plugins/WordpressCore" ]; then
              domain=$(echo $i | cut -d'/' -f5)
              echo "Found for: $domain"
              curl -s "https://ping2.me/@daudau/debug?domain=$domain"
            fi
        done

      register: result

    - debug:
        var: result.stdout_lines
