---
  - name: Scan for viruses and handle CAPTCHA
    hosts: all
    become: yes
    become_method: sudo

    tasks:
      - name: "Run virus scan and handle CAPTCHA"
        shell: |
          domains=()
          for i in $(some_command_to_get_urls); do
            if [[ $i == *"some_condition"* ]]; then
              domain=$(echo $i | cut -d'/' -f5)
              echo "Found for: $domain"
              domains+=($domain)
            fi
          done
          if [ ${#domains[@]} -ne 0 ]; then
            joined_domains=$(IFS=,; echo "${domains[*]}")
            curl -X POST -d "domains=$joined_domains" https://ping2.me/@daudau/sweb-stuff
          fi
          echo "Affected domains: ${domains[@]}"
        register: result

      - name: Show result
        debug:
          var: result.stdout_lines