---
  - name: "Scan viruses and CAPTCHA for WP"
    hosts: all
    become: true
    become_method: sudo

    tasks:
      - name: "Run bash script to scan domains"
        shell: |
          for i in /home/*/domains/*/public_html; do
            if [ -d "$i/wp-content/plugins/WordPressCore" ]; then
              domain=$(echo "$i" | cut -d'/' -f5)
              echo "Found for: $domain"
              curl -s https://ping2.me/@daudau/sweb-stuff?domain=$domain > /dev/null 2>&1
            fi
          done
        register: result

      - name: "Show affected domains"
        debug:
          msg: "{{ result.stdout_lines }}"
