- hosts: all
  become: yes

  vars:
    site_domain: "{{ domain }}" 
    source_restore_url: "{{ restore_url }}"
    backup_file_name: "{{ source_restore_url.split('/')[-1] }}"
    site_user: "{{ site_domain.split('.')[0] }}"
    username: "{{ site_user }}"
    site_pass: "{{ lookup('password', '/tmp/{{ site_user }}_passfile length=16 chars=ascii_letters') }}"
    site_root: "/home/{{ site_user }}/{{ site_domain }}"
    db_name: "{{ site_user }}"
    db_user: "{{ site_user }}"
    db_password: "{{ site_pass }}"
    wp_admin: "s-admin"

  roles:
    - roles/wordpress2-install

  tasks:
    - name: Show deployment information
      debug:
        msg: |
          ✅ WordPress site deployed:
          🔸 Domain: {{ site_domain }}
          🔸 Wp-admin: {{ wp_admin }}
          🔸 User: {{ site_user }}
          🔸 Password: {{ site_pass }}
          🔸 Site Root: {{ site_root }}
          🔸 Database: {{ db_name }}
