- hosts: all
  become: yes

  vars:
    site_domain: "{{ domain }}" 
    site_user: "{{ site_domain.split('.')[0] }}"
    username: "{{ site_user }}"
    site_pass: "{{ lookup('password', '/tmp/{{ site_user }}_passfile length=16 chars=ascii_letters') }}"
    site_root: "/home/{{ site_user }}/{{ site_domain }}"
    db_name: "{{ site_user }}"
    db_user: "{{ site_user }}"
    db_password: "{{ site_pass }}"

  roles:
    - roles/wordpress2-install

  tasks:
    - name: Show deployment information
      debug:
        msg: |
          ✅ WordPress site deployed:
          🔸 Domain: {{ site_domain }}
          🔸 User: {{ site_user }}
          🔸 Password: {{ site_pass }}
          🔸 Site Root: {{ site_root }}
          🔸 Database: {{ db_name }}
